# Generated by Django 6.0 on 2025-12-18 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variables', models.JSONField(default=list, help_text='List of template variables')),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('new_offer', 'New Offer'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('payment_confirmed', 'Payment Confirmed'), ('work_submitted', 'Work Submitted'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('revision_requested', 'Revision Requested'), ('deadline_reminder', 'Deadline Reminder')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('chat_id', models.UUIDField(blank=True, null=True)),
                ('offer_id', models.UUIDField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, help_text='Additional notification data')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_new_message', models.BooleanField(default=True)),
                ('email_new_offer', models.BooleanField(default=True)),
                ('email_offer_accepted', models.BooleanField(default=True)),
                ('email_payment_confirmed', models.BooleanField(default=True)),
                ('email_work_submitted', models.BooleanField(default=True)),
                ('email_order_completed', models.BooleanField(default=True)),
                ('email_deadline_reminder', models.BooleanField(default=True)),
                ('in_app_new_message', models.BooleanField(default=True)),
                ('in_app_new_offer', models.BooleanField(default=True)),
                ('in_app_offer_accepted', models.BooleanField(default=True)),
                ('in_app_payment_confirmed', models.BooleanField(default=True)),
                ('in_app_work_submitted', models.BooleanField(default=True)),
                ('in_app_order_completed', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
