# Generated by Django 6.0 on 2025-12-18 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('delivery_time', models.PositiveIntegerField()),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for revision')),
            ],
            options={
                'db_table': 'offer_revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('delivery_time', models.PositiveIntegerField(help_text='Delivery time in days')),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='For hourly offers', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('milestones', models.JSONField(default=list, help_text='List of milestone objects')),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='chat.chat')),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
